# CSCI124 - Ass1
# sja998
# makefile - supports multi-file compilation
CC=g++

CFLAG= -c -Wall

all: mainass1

mainass1:
	$(CC) $(CFLAGS) main.cpp ass1.cpp ass1.h -o main.o

clean:
	rm -rf *.o mainass1
